# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import AddonProfile
    from ._models_py3 import AppResource
    from ._models_py3 import AppResourceProperties
    from ._models_py3 import DeploymentInstance
    from ._models_py3 import DeploymentResource
    from ._models_py3 import DeploymentResourceProperties
    from ._models_py3 import DeploymentSettings
    from ._models_py3 import ProxyResource
    from ._models_py3 import Resource
    from ._models_py3 import ResourceUploadDefinition
    from ._models_py3 import Sku
    from ._models_py3 import TanzuClusterResource
    from ._models_py3 import TanzuClusterResourceProperties
    from ._models_py3 import TrackedResource
    from ._models_py3 import UserSourceInfo
except (SyntaxError, ImportError):
    from ._models import AddonProfile
    from ._models import AppResource
    from ._models import AppResourceProperties
    from ._models import DeploymentInstance
    from ._models import DeploymentResource
    from ._models import DeploymentResourceProperties
    from ._models import DeploymentSettings
    from ._models import ProxyResource
    from ._models import Resource
    from ._models import ResourceUploadDefinition
    from ._models import Sku
    from ._models import TanzuClusterResource
    from ._models import TanzuClusterResourceProperties
    from ._models import TrackedResource
    from ._models import UserSourceInfo
from ._paged_models import AppResourcePaged
from ._paged_models import DeploymentResourcePaged
from ._app_platform_management_client_enums import (
    ProvisioningState,
    AppResourceProvisioningState,
    DeploymentResourceProvisioningState,
    DeploymentResourceStatus,
)

__all__ = [
    'AddonProfile',
    'AppResource',
    'AppResourceProperties',
    'DeploymentInstance',
    'DeploymentResource',
    'DeploymentResourceProperties',
    'DeploymentSettings',
    'ProxyResource',
    'Resource',
    'ResourceUploadDefinition',
    'Sku',
    'TanzuClusterResource',
    'TanzuClusterResourceProperties',
    'TrackedResource',
    'UserSourceInfo',
    'AppResourcePaged',
    'DeploymentResourcePaged',
    'ProvisioningState',
    'AppResourceProvisioningState',
    'DeploymentResourceProvisioningState',
    'DeploymentResourceStatus',
]
